//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config'
import linguiPlugin from 'eslint-plugin-lingui'

export default [
  ...tanstackConfig,
  linguiPlugin.configs['flat/recommended'],
  {
    rules: {
      'import/no-cycle': 'off',
      'import/order': 'off',
      'sort-imports': 'off',
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/require-await': 'off',
      'pnpm/json-enforce-catalog': 'off',
      'lingui/no-unlocalized-strings': [
        'warn',
        {
          ignore: [
            '^[^A-Za-z]+$',
            '^https?://',
            '^/[a-z]',
            '^[a-z][a-z0-9_-]*$',
            '^\\.[a-z0-9]+$',
            '^__.*__$',
            '^[a-z][a-zA-Z0-9_]*\\.[a-z][a-zA-Z0-9_.]*$',
            '^[A-Z][A-Z0-9_]+$',
            '^es-[A-Z]{2}$',
            '^en-[A-Z]{2}$',
            '^[A-Za-z]+/[A-Za-z][A-Za-z0-9_-]*$',
            '^application/',
            '^text/',
            '^image/',
            '^video/',
            '^audio/',
            '^multipart/',
          ],
          ignoreNames: [
            'className',
            'classNames',
            'class',
            'style',
            'styles',
            'id',
            'key',
            'type',
            'name',
            'role',
            'href',
            'src',
            'alt',
            'rel',
            'target',
            'as',
            'variant',
            'size',
            'color',
            'data-testid',
            'data-ticket',
            'data-slot',
            'aria-hidden',
            'displayName',
            'tone',
            'intent',
            'method',
            'from',
            'to',
            'path',
            'pathname',
            'redirect',
            'mode',
            'autoComplete',
            'inputMode',
            'enterKeyHint',
            'accept',
            'encType',
            'sameSite',
            'crossOrigin',
            'referrerPolicy',
            'fetchPriority',
            'loading',
            'decoding',
            'event_type',
            'eventType',
            'deliverable_status',
            'status',
            'stage',
            'step',
            'severity',
            'direction',
            'orientation',
            'shape',
            'side',
            'align',
            'placement',
            'platform',
            'provider',
            'kind',
            'category',
            'group',
            'level',
            'tier',
            'currency',
            'locale',
            'lang',
            'language',
            'field',
            'day',
            'month',
            'year',
            'pattern',
          ],
          ignoreFunctions: [
            'cn',
            'cva',
            'tv',
            'clsx',
            'classnames',
            'console.*',
            'Error',
            'z.*',
            't',
            'msg',
            'plural',
            'select',
            'selectOrdinal',
            'track',
            'identify',
            'page',
            'capture',
            'sessionStorage.*',
            'localStorage.*',
            '*.setField',
            '*.setFieldValue',
            'setField',
            '*.setItem',
            '*.getItem',
            '*.removeItem',
            '*.toLocaleString',
            '*.toLocaleDateString',
            '*.toLocaleTimeString',
            '*.toString',
            'getStepIndex',
            'getQueryKey',
            'createServerFn',
            'createFileRoute',
            'redirect',
            'navigate',
            'router.navigate',
            '*.invalidateQueries',
            '*.setQueryData',
            '*.getQueryData',
            '*.prefetchQuery',
            'queryClient.*',
            'useQuery',
            'useMutation',
            'useSuspenseQuery',
            'document.querySelector',
            'document.getElementById',
            'document.createElement',
            'getComputedStyle',
            'window.matchMedia',
            'setAttribute',
            'getAttribute',
            'classList.*',
            'fetch',
            'URL',
            'URLSearchParams',
            'new RegExp',
            'useTrackOnceVisible',
            'trackLinkCardSeen',
            'trackDraftCardSeen',
            '*.find',
            '*.filter',
            '*.map',
            'extractSnapshot',
            'extractPreviewOutcome',
          ],
        },
      ],
    },
  },
  {
    files: ['**/*.{test,spec}.{ts,tsx}', 'src/test/**', '**/__tests__/**'],
    rules: {
      'lingui/no-unlocalized-strings': 'off',
    },
  },
  {
    files: [
      '**/*.config.{js,ts}',
      'scripts/**/*',
      'src/routeTree.gen.ts',
      'src/env.ts',
      'src/router.tsx',
      'src/routes/ds.tsx',
      'src/routes/ds-onboarding.tsx',
      'src/features/campaigns/brief-builder/test-utils.tsx',
      'src/features/discovery/campaign-board/search-schema.ts',
      'src/features/earnings/utils/exportCsv.ts',
      'src/features/earnings/hooks/useExportCreatorEarnings.ts',
      'src/routes/_creator/earnings.tsx',
      'src/**/use*Query.ts',
      'src/**/use*Subscription.ts',
      'src/**/useConfigurationWebSocket.ts',
      'src/**/analytics.ts',
      'src/**/analytics/**',
      'src/**/api/**',
      'src/**/queryKeys.ts',
      'src/shared/**',
      'src/components/ui/**',
      '**/schemas.ts',
      '**/types.ts',
      '**/store.ts',
    ],
    rules: {
      'lingui/no-unlocalized-strings': 'off',
    },
  },
  {
    files: ['src/**/*.{ts,tsx}'],
    ignores: ['src/test/**', 'src/shared/api/test-mutator.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                '**/shared/api/test-generated/**',
                '**/shared/api/test-mutator',
                '#/shared/api/test-generated/**',
                '#/shared/api/test-mutator',
              ],
              message:
                'Test-only API client. Only importable from src/test/**.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/test/e2e/**', 'src/test/e2e/fixtures.ts'],
    rules: {
      'react-hooks/rules-of-hooks': 'off',
    },
  },
  {
    ignores: [
      'eslint.config.js',
      'prettier.config.js',
      'LOST_COMMITS.md',
      'dist/**',
      'node_modules/**',
      'playwright-report/**',
      'test-results/**',
      'src/test/**',
      '**/*.test.ts',
      '**/*.test.tsx',
      '**/*.spec.ts',
      '**/*.spec.tsx',
      'src/shared/api/generated/**',
      'src/shared/api/test-generated/**',
      'src/routeTree.gen.ts',
      '.rafita/**',
      '.flow/**',
    ],
  },
]
