/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */

export interface CreateTestConversationResponse {
  conversation_id: string
  brand_account_id: string
  creator_account_id: string
  brand_workspace_id: string
  /** Only present when the request included seed_offer_ready. */
  campaign_id?: string
}
