/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */

export * from './accountKind'
export * from './brandWorkspaceSummary'
export * from './createTestAccountRequest'
export * from './createTestConversationRequest'
export * from './createTestConversationResponse'
export * from './creatorProfile'
export * from './creatorProfileBestVideosItem'
export * from './error'
export * from './errorError'
export * from './errorErrorDetails'
export * from './meResponse'
export * from './onboardingStatus'
export * from './onboardTestAccountFullRequest'
export * from './purgeTestAccountsRequest'
export * from './purgeTestAccountsResponse'
export * from './seedMessagesInput'
export * from './seedMessagesInputMarkReadFor'
export * from './seedOfferReadyInput'
export * from './setTestOnboardingRequest'
