/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Marz Test API
 * Test-only contract for E2E fixtures. All endpoints require `X-Test-Secret`
and are gated by `TEST_API_ENABLED=true`. Never available in production.

Consumed by marz-front E2E suite via a separate Orval generation target so
the production client stays free of test-only types.

 * OpenAPI spec version: 0.1.0
 */

/**
 * When present, the endpoint also creates an active campaign in the
brand workspace plus an accepted application from the creator,
leaving the (campaign_id, conversation_id) pair ready for an
immediate POST /v1/offers call.

 */
export interface SeedOfferReadyInput {
  /** @minLength 1 */
  campaign_name: string
  /**
   * ISO-4217 3-letter currency code, uppercased.
   * @minLength 3
   * @maxLength 3
   */
  currency: string
}
