import { existsSync, readFileSync } from 'node:fs'
import { writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { execSync } from 'node:child_process'
import {
  diffSpecs,
  isEmptyDiff,
  renderChangelogEntry,
} from './lib/openapi-diff.ts'
import type { SpecDiff } from './lib/openapi-diff.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const CHANGELOG_PATH = resolve(root, 'openapi/CHANGELOG.md')

export interface AppendOptions {
  label: string
  oldSpec: unknown
  newSpec: unknown
  timestamp?: string
}

const LAST_RUN_MARKER = '<!-- last-run -->'

export interface AppendResult {
  diff: SpecDiff
  entry: string
}

export async function appendChangelog({
  label,
  oldSpec,
  newSpec,
  timestamp = new Date().toISOString(),
}: AppendOptions): Promise<AppendResult | null> {
  const diff = diffSpecs(oldSpec, newSpec)
  if (isEmptyDiff(diff)) return null

  const entry = renderChangelogEntry(label, timestamp, diff)
  const markedEntry = `${LAST_RUN_MARKER}\n${entry}`
  const raw = existsSync(CHANGELOG_PATH)
    ? readFileSync(CHANGELOG_PATH, 'utf-8')
    : '# OpenAPI changelog\n\nAuto-generated by `pnpm api:sync`. Newest first.\n\n'

  // strip any previous last-run marker line before re-inserting
  const existing = raw
    .split('\n')
    .filter((line) => line.trim() !== LAST_RUN_MARKER)
    .join('\n')

  const headerEnd = existing.indexOf('\n## ')
  const next =
    headerEnd === -1
      ? existing.trimEnd() + '\n\n' + markedEntry
      : existing.slice(0, headerEnd + 1) +
        '\n' +
        markedEntry +
        existing.slice(headerEnd)

  await writeFile(CHANGELOG_PATH, next)
  return { diff, entry }
}

function loadJson(path: string): unknown | null {
  if (!existsSync(path)) return null
  try {
    return JSON.parse(readFileSync(path, 'utf-8'))
  } catch {
    return null
  }
}

function loadFromGit(path: string): unknown | null {
  try {
    const rel = path.startsWith(root) ? path.slice(root.length + 1) : path
    const out = execSync(`git show HEAD:${rel}`, {
      cwd: root,
      stdio: ['ignore', 'pipe', 'ignore'],
    })
    return JSON.parse(out.toString('utf-8'))
  } catch {
    return null
  }
}

// CLI: compare working-tree spec vs HEAD-committed spec
async function runCli() {
  const targets: { label: string; path: string }[] = [
    { label: 'prod', path: resolve(root, 'openapi/spec.json') },
    { label: 'test', path: resolve(root, 'openapi/test-spec.json') },
  ]

  let any = false
  for (const { label, path } of targets) {
    const current = loadJson(path)
    if (!current) {
      console.log(
        `[openapi-changelog] ${label}: no current spec at ${path}, skipping`,
      )
      continue
    }
    const previous = loadFromGit(path)
    if (!previous) {
      console.log(
        `[openapi-changelog] ${label}: no committed baseline in HEAD, skipping`,
      )
      continue
    }
    const result = await appendChangelog({
      label,
      oldSpec: previous,
      newSpec: current,
    })
    if (result) {
      any = true
      const { diff, entry } = result
      console.log(
        `[openapi-changelog] ${label}: +${String(diff.addedOps.length)} ops, -${String(diff.removedOps.length)} ops, ~${String(diff.changedOps.length)} ops, schemas +${String(diff.addedSchemas.length)}/-${String(diff.removedSchemas.length)}/~${String(diff.changedSchemas.length)}`,
      )
      process.stdout.write(entry.trimEnd() + '\n')
    } else {
      console.log(`[openapi-changelog] ${label}: no changes`)
    }
  }
  if (any) console.log(`[openapi-changelog] entry written to ${CHANGELOG_PATH}`)
}

const isMain =
  process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (isMain) {
  await runCli()
}
