/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DsOnboardingRouteImport } from './routes/ds-onboarding'
import { Route as DsRouteImport } from './routes/ds'
import { Route as CreatorRouteImport } from './routes/_creator'
import { Route as BrandRouteImport } from './routes/_brand'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthLinkInvalidRouteImport } from './routes/auth/link-invalid'
import { Route as CreatorOffersRouteImport } from './routes/_creator/offers'
import { Route as BrandCampaignsRouteImport } from './routes/_brand/campaigns'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DsOnboardingRoute = DsOnboardingRouteImport.update({
  id: '/ds-onboarding',
  path: '/ds-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DsRoute = DsRouteImport.update({
  id: '/ds',
  path: '/ds',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/_creator',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/_brand',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLinkInvalidRoute = AuthLinkInvalidRouteImport.update({
  id: '/auth/link-invalid',
  path: '/auth/link-invalid',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorOffersRoute = CreatorOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => CreatorRoute,
} as any)
const BrandCampaignsRoute = BrandCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => BrandRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ds': typeof DsRoute
  '/ds-onboarding': typeof DsOnboardingRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/campaigns': typeof BrandCampaignsRoute
  '/offers': typeof CreatorOffersRoute
  '/auth/link-invalid': typeof AuthLinkInvalidRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ds': typeof DsRoute
  '/ds-onboarding': typeof DsOnboardingRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/campaigns': typeof BrandCampaignsRoute
  '/offers': typeof CreatorOffersRoute
  '/auth/link-invalid': typeof AuthLinkInvalidRoute
  '/auth': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_brand': typeof BrandRouteWithChildren
  '/_creator': typeof CreatorRouteWithChildren
  '/ds': typeof DsRoute
  '/ds-onboarding': typeof DsOnboardingRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/_brand/campaigns': typeof BrandCampaignsRoute
  '/_creator/offers': typeof CreatorOffersRoute
  '/auth/link-invalid': typeof AuthLinkInvalidRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ds'
    | '/ds-onboarding'
    | '/health'
    | '/login'
    | '/campaigns'
    | '/offers'
    | '/auth/link-invalid'
    | '/auth/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ds'
    | '/ds-onboarding'
    | '/health'
    | '/login'
    | '/campaigns'
    | '/offers'
    | '/auth/link-invalid'
    | '/auth'
  id:
    | '__root__'
    | '/'
    | '/_brand'
    | '/_creator'
    | '/ds'
    | '/ds-onboarding'
    | '/health'
    | '/login'
    | '/_brand/campaigns'
    | '/_creator/offers'
    | '/auth/link-invalid'
    | '/auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRouteWithChildren
  CreatorRoute: typeof CreatorRouteWithChildren
  DsRoute: typeof DsRoute
  DsOnboardingRoute: typeof DsOnboardingRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  AuthLinkInvalidRoute: typeof AuthLinkInvalidRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds-onboarding': {
      id: '/ds-onboarding'
      path: '/ds-onboarding'
      fullPath: '/ds-onboarding'
      preLoaderRoute: typeof DsOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds': {
      id: '/ds'
      path: '/ds'
      fullPath: '/ds'
      preLoaderRoute: typeof DsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_creator': {
      id: '/_creator'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_brand': {
      id: '/_brand'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/link-invalid': {
      id: '/auth/link-invalid'
      path: '/auth/link-invalid'
      fullPath: '/auth/link-invalid'
      preLoaderRoute: typeof AuthLinkInvalidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_creator/offers': {
      id: '/_creator/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof CreatorOffersRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/_brand/campaigns': {
      id: '/_brand/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof BrandCampaignsRouteImport
      parentRoute: typeof BrandRoute
    }
  }
}

interface BrandRouteChildren {
  BrandCampaignsRoute: typeof BrandCampaignsRoute
}

const BrandRouteChildren: BrandRouteChildren = {
  BrandCampaignsRoute: BrandCampaignsRoute,
}

const BrandRouteWithChildren = BrandRoute._addFileChildren(BrandRouteChildren)

interface CreatorRouteChildren {
  CreatorOffersRoute: typeof CreatorOffersRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorOffersRoute: CreatorOffersRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRouteWithChildren,
  CreatorRoute: CreatorRouteWithChildren,
  DsRoute: DsRoute,
  DsOnboardingRoute: DsOnboardingRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  AuthLinkInvalidRoute: AuthLinkInvalidRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
