/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DsOnboardingRouteImport } from './routes/ds-onboarding'
import { Route as DsRouteImport } from './routes/ds'
import { Route as DesktopOnlyRouteImport } from './routes/desktop-only'
import { Route as CreatorRouteImport } from './routes/_creator'
import { Route as BrandRouteImport } from './routes/_brand'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as OnboardingCreatorRouteImport } from './routes/onboarding/creator'
import { Route as OnboardingBrandRouteImport } from './routes/onboarding/brand'
import { Route as AuthLinkInvalidRouteImport } from './routes/auth/link-invalid'
import { Route as AuthKindRouteImport } from './routes/auth/kind'
import { Route as AuthCheckEmailRouteImport } from './routes/auth/check-email'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as CreatorOffersRouteImport } from './routes/_creator/offers'
import { Route as CreatorEarningsRouteImport } from './routes/_creator/earnings'
import { Route as CreatorCampaignsRouteImport } from './routes/_creator/campaigns'
import { Route as BrandPaymentsRouteImport } from './routes/_brand/payments'
import { Route as BrandCampaignsRouteImport } from './routes/_brand/campaigns'
import { Route as OnboardingCreatorIndexRouteImport } from './routes/onboarding/creator.index'
import { Route as OnboardingBrandIndexRouteImport } from './routes/onboarding/brand.index'
import { Route as BrandCampaignsIndexRouteImport } from './routes/_brand/campaigns.index'
import { Route as WorkspaceConversationsConversationIdRouteImport } from './routes/workspace.conversations.$conversationId'
import { Route as OnboardingCreatorStepRouteImport } from './routes/onboarding/creator.$step'
import { Route as OnboardingBrandStepRouteImport } from './routes/onboarding/brand.$step'
import { Route as BrandCampaignsNewRouteImport } from './routes/_brand/campaigns.new'
import { Route as BrandCampaignsCampaignIdRouteImport } from './routes/_brand/campaigns.$campaignId'
import { Route as BrandCampaignsNewIndexRouteImport } from './routes/_brand/campaigns.new.index'
import { Route as BrandCampaignsNewPhaseRouteImport } from './routes/_brand/campaigns.new.$phase'
import { Route as BrandCampaignsCampaignIdConfigurationRouteImport } from './routes/_brand/campaigns.$campaignId.configuration'
import { Route as BrandCampaignsCampaignIdBriefRouteImport } from './routes/_brand/campaigns.$campaignId.brief'
import { Route as BrandCampaignsCampaignIdConfigurationStepRouteImport } from './routes/_brand/campaigns.$campaignId.configuration.$step'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DsOnboardingRoute = DsOnboardingRouteImport.update({
  id: '/ds-onboarding',
  path: '/ds-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DsRoute = DsRouteImport.update({
  id: '/ds',
  path: '/ds',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopOnlyRoute = DesktopOnlyRouteImport.update({
  id: '/desktop-only',
  path: '/desktop-only',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/_creator',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/_brand',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCreatorRoute = OnboardingCreatorRouteImport.update({
  id: '/onboarding/creator',
  path: '/onboarding/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBrandRoute = OnboardingBrandRouteImport.update({
  id: '/onboarding/brand',
  path: '/onboarding/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLinkInvalidRoute = AuthLinkInvalidRouteImport.update({
  id: '/auth/link-invalid',
  path: '/auth/link-invalid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthKindRoute = AuthKindRouteImport.update({
  id: '/auth/kind',
  path: '/auth/kind',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/auth/check-email',
  path: '/auth/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorOffersRoute = CreatorOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorEarningsRoute = CreatorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorCampaignsRoute = CreatorCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => CreatorRoute,
} as any)
const BrandPaymentsRoute = BrandPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => BrandRoute,
} as any)
const BrandCampaignsRoute = BrandCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => BrandRoute,
} as any)
const OnboardingCreatorIndexRoute = OnboardingCreatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingCreatorRoute,
} as any)
const OnboardingBrandIndexRoute = OnboardingBrandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingBrandRoute,
} as any)
const BrandCampaignsIndexRoute = BrandCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandCampaignsRoute,
} as any)
const WorkspaceConversationsConversationIdRoute =
  WorkspaceConversationsConversationIdRouteImport.update({
    id: '/conversations/$conversationId',
    path: '/conversations/$conversationId',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const OnboardingCreatorStepRoute = OnboardingCreatorStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => OnboardingCreatorRoute,
} as any)
const OnboardingBrandStepRoute = OnboardingBrandStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => OnboardingBrandRoute,
} as any)
const BrandCampaignsNewRoute = BrandCampaignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BrandCampaignsRoute,
} as any)
const BrandCampaignsCampaignIdRoute =
  BrandCampaignsCampaignIdRouteImport.update({
    id: '/$campaignId',
    path: '/$campaignId',
    getParentRoute: () => BrandCampaignsRoute,
  } as any)
const BrandCampaignsNewIndexRoute = BrandCampaignsNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandCampaignsNewRoute,
} as any)
const BrandCampaignsNewPhaseRoute = BrandCampaignsNewPhaseRouteImport.update({
  id: '/$phase',
  path: '/$phase',
  getParentRoute: () => BrandCampaignsNewRoute,
} as any)
const BrandCampaignsCampaignIdConfigurationRoute =
  BrandCampaignsCampaignIdConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => BrandCampaignsCampaignIdRoute,
  } as any)
const BrandCampaignsCampaignIdBriefRoute =
  BrandCampaignsCampaignIdBriefRouteImport.update({
    id: '/brief',
    path: '/brief',
    getParentRoute: () => BrandCampaignsCampaignIdRoute,
  } as any)
const BrandCampaignsCampaignIdConfigurationStepRoute =
  BrandCampaignsCampaignIdConfigurationStepRouteImport.update({
    id: '/$step',
    path: '/$step',
    getParentRoute: () => BrandCampaignsCampaignIdConfigurationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desktop-only': typeof DesktopOnlyRoute
  '/ds': typeof DsRoute
  '/ds-onboarding': typeof DsOnboardingRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/campaigns': typeof CreatorCampaignsRoute
  '/payments': typeof BrandPaymentsRoute
  '/earnings': typeof CreatorEarningsRoute
  '/offers': typeof CreatorOffersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/kind': typeof AuthKindRoute
  '/auth/link-invalid': typeof AuthLinkInvalidRoute
  '/onboarding/brand': typeof OnboardingBrandRouteWithChildren
  '/onboarding/creator': typeof OnboardingCreatorRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/campaigns/$campaignId': typeof BrandCampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof BrandCampaignsNewRouteWithChildren
  '/onboarding/brand/$step': typeof OnboardingBrandStepRoute
  '/onboarding/creator/$step': typeof OnboardingCreatorStepRoute
  '/workspace/conversations/$conversationId': typeof WorkspaceConversationsConversationIdRoute
  '/campaigns/': typeof BrandCampaignsIndexRoute
  '/onboarding/brand/': typeof OnboardingBrandIndexRoute
  '/onboarding/creator/': typeof OnboardingCreatorIndexRoute
  '/campaigns/$campaignId/brief': typeof BrandCampaignsCampaignIdBriefRoute
  '/campaigns/$campaignId/configuration': typeof BrandCampaignsCampaignIdConfigurationRouteWithChildren
  '/campaigns/new/$phase': typeof BrandCampaignsNewPhaseRoute
  '/campaigns/new/': typeof BrandCampaignsNewIndexRoute
  '/campaigns/$campaignId/configuration/$step': typeof BrandCampaignsCampaignIdConfigurationStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desktop-only': typeof DesktopOnlyRoute
  '/ds': typeof DsRoute
  '/ds-onboarding': typeof DsOnboardingRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRoute
  '/payments': typeof BrandPaymentsRoute
  '/campaigns': typeof BrandCampaignsIndexRoute
  '/earnings': typeof CreatorEarningsRoute
  '/offers': typeof CreatorOffersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/kind': typeof AuthKindRoute
  '/auth/link-invalid': typeof AuthLinkInvalidRoute
  '/auth': typeof AuthIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/campaigns/$campaignId': typeof BrandCampaignsCampaignIdRouteWithChildren
  '/onboarding/brand/$step': typeof OnboardingBrandStepRoute
  '/onboarding/creator/$step': typeof OnboardingCreatorStepRoute
  '/workspace/conversations/$conversationId': typeof WorkspaceConversationsConversationIdRoute
  '/onboarding/brand': typeof OnboardingBrandIndexRoute
  '/onboarding/creator': typeof OnboardingCreatorIndexRoute
  '/campaigns/$campaignId/brief': typeof BrandCampaignsCampaignIdBriefRoute
  '/campaigns/$campaignId/configuration': typeof BrandCampaignsCampaignIdConfigurationRouteWithChildren
  '/campaigns/new/$phase': typeof BrandCampaignsNewPhaseRoute
  '/campaigns/new': typeof BrandCampaignsNewIndexRoute
  '/campaigns/$campaignId/configuration/$step': typeof BrandCampaignsCampaignIdConfigurationStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_brand': typeof BrandRouteWithChildren
  '/_creator': typeof CreatorRouteWithChildren
  '/desktop-only': typeof DesktopOnlyRoute
  '/ds': typeof DsRoute
  '/ds-onboarding': typeof DsOnboardingRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/_brand/campaigns': typeof BrandCampaignsRouteWithChildren
  '/_brand/payments': typeof BrandPaymentsRoute
  '/_creator/campaigns': typeof CreatorCampaignsRoute
  '/_creator/earnings': typeof CreatorEarningsRoute
  '/_creator/offers': typeof CreatorOffersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/kind': typeof AuthKindRoute
  '/auth/link-invalid': typeof AuthLinkInvalidRoute
  '/onboarding/brand': typeof OnboardingBrandRouteWithChildren
  '/onboarding/creator': typeof OnboardingCreatorRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/_brand/campaigns/$campaignId': typeof BrandCampaignsCampaignIdRouteWithChildren
  '/_brand/campaigns/new': typeof BrandCampaignsNewRouteWithChildren
  '/onboarding/brand/$step': typeof OnboardingBrandStepRoute
  '/onboarding/creator/$step': typeof OnboardingCreatorStepRoute
  '/workspace/conversations/$conversationId': typeof WorkspaceConversationsConversationIdRoute
  '/_brand/campaigns/': typeof BrandCampaignsIndexRoute
  '/onboarding/brand/': typeof OnboardingBrandIndexRoute
  '/onboarding/creator/': typeof OnboardingCreatorIndexRoute
  '/_brand/campaigns/$campaignId/brief': typeof BrandCampaignsCampaignIdBriefRoute
  '/_brand/campaigns/$campaignId/configuration': typeof BrandCampaignsCampaignIdConfigurationRouteWithChildren
  '/_brand/campaigns/new/$phase': typeof BrandCampaignsNewPhaseRoute
  '/_brand/campaigns/new/': typeof BrandCampaignsNewIndexRoute
  '/_brand/campaigns/$campaignId/configuration/$step': typeof BrandCampaignsCampaignIdConfigurationStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desktop-only'
    | '/ds'
    | '/ds-onboarding'
    | '/health'
    | '/inbox'
    | '/workspace'
    | '/campaigns'
    | '/payments'
    | '/earnings'
    | '/offers'
    | '/auth/callback'
    | '/auth/check-email'
    | '/auth/kind'
    | '/auth/link-invalid'
    | '/onboarding/brand'
    | '/onboarding/creator'
    | '/auth/'
    | '/workspace/'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/onboarding/brand/$step'
    | '/onboarding/creator/$step'
    | '/workspace/conversations/$conversationId'
    | '/campaigns/'
    | '/onboarding/brand/'
    | '/onboarding/creator/'
    | '/campaigns/$campaignId/brief'
    | '/campaigns/$campaignId/configuration'
    | '/campaigns/new/$phase'
    | '/campaigns/new/'
    | '/campaigns/$campaignId/configuration/$step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desktop-only'
    | '/ds'
    | '/ds-onboarding'
    | '/health'
    | '/inbox'
    | '/payments'
    | '/campaigns'
    | '/earnings'
    | '/offers'
    | '/auth/callback'
    | '/auth/check-email'
    | '/auth/kind'
    | '/auth/link-invalid'
    | '/auth'
    | '/workspace'
    | '/campaigns/$campaignId'
    | '/onboarding/brand/$step'
    | '/onboarding/creator/$step'
    | '/workspace/conversations/$conversationId'
    | '/onboarding/brand'
    | '/onboarding/creator'
    | '/campaigns/$campaignId/brief'
    | '/campaigns/$campaignId/configuration'
    | '/campaigns/new/$phase'
    | '/campaigns/new'
    | '/campaigns/$campaignId/configuration/$step'
  id:
    | '__root__'
    | '/'
    | '/_brand'
    | '/_creator'
    | '/desktop-only'
    | '/ds'
    | '/ds-onboarding'
    | '/health'
    | '/inbox'
    | '/workspace'
    | '/_brand/campaigns'
    | '/_brand/payments'
    | '/_creator/campaigns'
    | '/_creator/earnings'
    | '/_creator/offers'
    | '/auth/callback'
    | '/auth/check-email'
    | '/auth/kind'
    | '/auth/link-invalid'
    | '/onboarding/brand'
    | '/onboarding/creator'
    | '/auth/'
    | '/workspace/'
    | '/_brand/campaigns/$campaignId'
    | '/_brand/campaigns/new'
    | '/onboarding/brand/$step'
    | '/onboarding/creator/$step'
    | '/workspace/conversations/$conversationId'
    | '/_brand/campaigns/'
    | '/onboarding/brand/'
    | '/onboarding/creator/'
    | '/_brand/campaigns/$campaignId/brief'
    | '/_brand/campaigns/$campaignId/configuration'
    | '/_brand/campaigns/new/$phase'
    | '/_brand/campaigns/new/'
    | '/_brand/campaigns/$campaignId/configuration/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRouteWithChildren
  CreatorRoute: typeof CreatorRouteWithChildren
  DesktopOnlyRoute: typeof DesktopOnlyRoute
  DsRoute: typeof DsRoute
  DsOnboardingRoute: typeof DsOnboardingRoute
  HealthRoute: typeof HealthRoute
  InboxRoute: typeof InboxRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthKindRoute: typeof AuthKindRoute
  AuthLinkInvalidRoute: typeof AuthLinkInvalidRoute
  OnboardingBrandRoute: typeof OnboardingBrandRouteWithChildren
  OnboardingCreatorRoute: typeof OnboardingCreatorRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds-onboarding': {
      id: '/ds-onboarding'
      path: '/ds-onboarding'
      fullPath: '/ds-onboarding'
      preLoaderRoute: typeof DsOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds': {
      id: '/ds'
      path: '/ds'
      fullPath: '/ds'
      preLoaderRoute: typeof DsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop-only': {
      id: '/desktop-only'
      path: '/desktop-only'
      fullPath: '/desktop-only'
      preLoaderRoute: typeof DesktopOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_creator': {
      id: '/_creator'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_brand': {
      id: '/_brand'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/creator': {
      id: '/onboarding/creator'
      path: '/onboarding/creator'
      fullPath: '/onboarding/creator'
      preLoaderRoute: typeof OnboardingCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/brand': {
      id: '/onboarding/brand'
      path: '/onboarding/brand'
      fullPath: '/onboarding/brand'
      preLoaderRoute: typeof OnboardingBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/link-invalid': {
      id: '/auth/link-invalid'
      path: '/auth/link-invalid'
      fullPath: '/auth/link-invalid'
      preLoaderRoute: typeof AuthLinkInvalidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/kind': {
      id: '/auth/kind'
      path: '/auth/kind'
      fullPath: '/auth/kind'
      preLoaderRoute: typeof AuthKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/check-email': {
      id: '/auth/check-email'
      path: '/auth/check-email'
      fullPath: '/auth/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_creator/offers': {
      id: '/_creator/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof CreatorOffersRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/_creator/earnings': {
      id: '/_creator/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof CreatorEarningsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/_creator/campaigns': {
      id: '/_creator/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CreatorCampaignsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/_brand/payments': {
      id: '/_brand/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof BrandPaymentsRouteImport
      parentRoute: typeof BrandRoute
    }
    '/_brand/campaigns': {
      id: '/_brand/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof BrandCampaignsRouteImport
      parentRoute: typeof BrandRoute
    }
    '/onboarding/creator/': {
      id: '/onboarding/creator/'
      path: '/'
      fullPath: '/onboarding/creator/'
      preLoaderRoute: typeof OnboardingCreatorIndexRouteImport
      parentRoute: typeof OnboardingCreatorRoute
    }
    '/onboarding/brand/': {
      id: '/onboarding/brand/'
      path: '/'
      fullPath: '/onboarding/brand/'
      preLoaderRoute: typeof OnboardingBrandIndexRouteImport
      parentRoute: typeof OnboardingBrandRoute
    }
    '/_brand/campaigns/': {
      id: '/_brand/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof BrandCampaignsIndexRouteImport
      parentRoute: typeof BrandCampaignsRoute
    }
    '/workspace/conversations/$conversationId': {
      id: '/workspace/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/workspace/conversations/$conversationId'
      preLoaderRoute: typeof WorkspaceConversationsConversationIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/onboarding/creator/$step': {
      id: '/onboarding/creator/$step'
      path: '/$step'
      fullPath: '/onboarding/creator/$step'
      preLoaderRoute: typeof OnboardingCreatorStepRouteImport
      parentRoute: typeof OnboardingCreatorRoute
    }
    '/onboarding/brand/$step': {
      id: '/onboarding/brand/$step'
      path: '/$step'
      fullPath: '/onboarding/brand/$step'
      preLoaderRoute: typeof OnboardingBrandStepRouteImport
      parentRoute: typeof OnboardingBrandRoute
    }
    '/_brand/campaigns/new': {
      id: '/_brand/campaigns/new'
      path: '/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof BrandCampaignsNewRouteImport
      parentRoute: typeof BrandCampaignsRoute
    }
    '/_brand/campaigns/$campaignId': {
      id: '/_brand/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof BrandCampaignsCampaignIdRouteImport
      parentRoute: typeof BrandCampaignsRoute
    }
    '/_brand/campaigns/new/': {
      id: '/_brand/campaigns/new/'
      path: '/'
      fullPath: '/campaigns/new/'
      preLoaderRoute: typeof BrandCampaignsNewIndexRouteImport
      parentRoute: typeof BrandCampaignsNewRoute
    }
    '/_brand/campaigns/new/$phase': {
      id: '/_brand/campaigns/new/$phase'
      path: '/$phase'
      fullPath: '/campaigns/new/$phase'
      preLoaderRoute: typeof BrandCampaignsNewPhaseRouteImport
      parentRoute: typeof BrandCampaignsNewRoute
    }
    '/_brand/campaigns/$campaignId/configuration': {
      id: '/_brand/campaigns/$campaignId/configuration'
      path: '/configuration'
      fullPath: '/campaigns/$campaignId/configuration'
      preLoaderRoute: typeof BrandCampaignsCampaignIdConfigurationRouteImport
      parentRoute: typeof BrandCampaignsCampaignIdRoute
    }
    '/_brand/campaigns/$campaignId/brief': {
      id: '/_brand/campaigns/$campaignId/brief'
      path: '/brief'
      fullPath: '/campaigns/$campaignId/brief'
      preLoaderRoute: typeof BrandCampaignsCampaignIdBriefRouteImport
      parentRoute: typeof BrandCampaignsCampaignIdRoute
    }
    '/_brand/campaigns/$campaignId/configuration/$step': {
      id: '/_brand/campaigns/$campaignId/configuration/$step'
      path: '/$step'
      fullPath: '/campaigns/$campaignId/configuration/$step'
      preLoaderRoute: typeof BrandCampaignsCampaignIdConfigurationStepRouteImport
      parentRoute: typeof BrandCampaignsCampaignIdConfigurationRoute
    }
  }
}

interface BrandCampaignsCampaignIdConfigurationRouteChildren {
  BrandCampaignsCampaignIdConfigurationStepRoute: typeof BrandCampaignsCampaignIdConfigurationStepRoute
}

const BrandCampaignsCampaignIdConfigurationRouteChildren: BrandCampaignsCampaignIdConfigurationRouteChildren =
  {
    BrandCampaignsCampaignIdConfigurationStepRoute:
      BrandCampaignsCampaignIdConfigurationStepRoute,
  }

const BrandCampaignsCampaignIdConfigurationRouteWithChildren =
  BrandCampaignsCampaignIdConfigurationRoute._addFileChildren(
    BrandCampaignsCampaignIdConfigurationRouteChildren,
  )

interface BrandCampaignsCampaignIdRouteChildren {
  BrandCampaignsCampaignIdBriefRoute: typeof BrandCampaignsCampaignIdBriefRoute
  BrandCampaignsCampaignIdConfigurationRoute: typeof BrandCampaignsCampaignIdConfigurationRouteWithChildren
}

const BrandCampaignsCampaignIdRouteChildren: BrandCampaignsCampaignIdRouteChildren =
  {
    BrandCampaignsCampaignIdBriefRoute: BrandCampaignsCampaignIdBriefRoute,
    BrandCampaignsCampaignIdConfigurationRoute:
      BrandCampaignsCampaignIdConfigurationRouteWithChildren,
  }

const BrandCampaignsCampaignIdRouteWithChildren =
  BrandCampaignsCampaignIdRoute._addFileChildren(
    BrandCampaignsCampaignIdRouteChildren,
  )

interface BrandCampaignsNewRouteChildren {
  BrandCampaignsNewPhaseRoute: typeof BrandCampaignsNewPhaseRoute
  BrandCampaignsNewIndexRoute: typeof BrandCampaignsNewIndexRoute
}

const BrandCampaignsNewRouteChildren: BrandCampaignsNewRouteChildren = {
  BrandCampaignsNewPhaseRoute: BrandCampaignsNewPhaseRoute,
  BrandCampaignsNewIndexRoute: BrandCampaignsNewIndexRoute,
}

const BrandCampaignsNewRouteWithChildren =
  BrandCampaignsNewRoute._addFileChildren(BrandCampaignsNewRouteChildren)

interface BrandCampaignsRouteChildren {
  BrandCampaignsCampaignIdRoute: typeof BrandCampaignsCampaignIdRouteWithChildren
  BrandCampaignsNewRoute: typeof BrandCampaignsNewRouteWithChildren
  BrandCampaignsIndexRoute: typeof BrandCampaignsIndexRoute
}

const BrandCampaignsRouteChildren: BrandCampaignsRouteChildren = {
  BrandCampaignsCampaignIdRoute: BrandCampaignsCampaignIdRouteWithChildren,
  BrandCampaignsNewRoute: BrandCampaignsNewRouteWithChildren,
  BrandCampaignsIndexRoute: BrandCampaignsIndexRoute,
}

const BrandCampaignsRouteWithChildren = BrandCampaignsRoute._addFileChildren(
  BrandCampaignsRouteChildren,
)

interface BrandRouteChildren {
  BrandCampaignsRoute: typeof BrandCampaignsRouteWithChildren
  BrandPaymentsRoute: typeof BrandPaymentsRoute
}

const BrandRouteChildren: BrandRouteChildren = {
  BrandCampaignsRoute: BrandCampaignsRouteWithChildren,
  BrandPaymentsRoute: BrandPaymentsRoute,
}

const BrandRouteWithChildren = BrandRoute._addFileChildren(BrandRouteChildren)

interface CreatorRouteChildren {
  CreatorCampaignsRoute: typeof CreatorCampaignsRoute
  CreatorEarningsRoute: typeof CreatorEarningsRoute
  CreatorOffersRoute: typeof CreatorOffersRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorCampaignsRoute: CreatorCampaignsRoute,
  CreatorEarningsRoute: CreatorEarningsRoute,
  CreatorOffersRoute: CreatorOffersRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceConversationsConversationIdRoute: typeof WorkspaceConversationsConversationIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceConversationsConversationIdRoute:
    WorkspaceConversationsConversationIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

interface OnboardingBrandRouteChildren {
  OnboardingBrandStepRoute: typeof OnboardingBrandStepRoute
  OnboardingBrandIndexRoute: typeof OnboardingBrandIndexRoute
}

const OnboardingBrandRouteChildren: OnboardingBrandRouteChildren = {
  OnboardingBrandStepRoute: OnboardingBrandStepRoute,
  OnboardingBrandIndexRoute: OnboardingBrandIndexRoute,
}

const OnboardingBrandRouteWithChildren = OnboardingBrandRoute._addFileChildren(
  OnboardingBrandRouteChildren,
)

interface OnboardingCreatorRouteChildren {
  OnboardingCreatorStepRoute: typeof OnboardingCreatorStepRoute
  OnboardingCreatorIndexRoute: typeof OnboardingCreatorIndexRoute
}

const OnboardingCreatorRouteChildren: OnboardingCreatorRouteChildren = {
  OnboardingCreatorStepRoute: OnboardingCreatorStepRoute,
  OnboardingCreatorIndexRoute: OnboardingCreatorIndexRoute,
}

const OnboardingCreatorRouteWithChildren =
  OnboardingCreatorRoute._addFileChildren(OnboardingCreatorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRouteWithChildren,
  CreatorRoute: CreatorRouteWithChildren,
  DesktopOnlyRoute: DesktopOnlyRoute,
  DsRoute: DsRoute,
  DsOnboardingRoute: DsOnboardingRoute,
  HealthRoute: HealthRoute,
  InboxRoute: InboxRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthKindRoute: AuthKindRoute,
  AuthLinkInvalidRoute: AuthLinkInvalidRoute,
  OnboardingBrandRoute: OnboardingBrandRouteWithChildren,
  OnboardingCreatorRoute: OnboardingCreatorRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
